using DotnetPkgsAiDocs.Analysis;

namespace DotnetPkgsAiDocs.Output;

/// <summary>
/// Generates Markdown output with embedded Mermaid diagrams for dependency graphs and public API surfaces.
/// </summary>
public static class MarkdownWriter
{
    /// <summary>
    /// Writes one dependencies-{tfm}.md file per TFM. Returns the list of files written.
    /// </summary>
    public static IReadOnlyList<string> WriteDependencyGraphPerTfm(
        string outputFolder,
        IReadOnlyList<DependencyResult> results,
        IReadOnlyList<string> firstPartyPrefixes)
    {
        var written = new List<string>();
        var byTfm = results
            .GroupBy(r => r.TargetFramework, StringComparer.OrdinalIgnoreCase)
            .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase);

        foreach (var tfmGroup in byTfm)
        {
            var tfm = tfmGroup.Key;
            var filePath = Path.Combine(outputFolder, $"dependencies-{tfm}.md");
            WriteDependencyGraphForTfm(filePath, tfm, tfmGroup.ToList(), firstPartyPrefixes);
            written.Add(filePath);
        }

        return written;
    }

    private static void WriteDependencyGraphForTfm(
        string outputPath,
        string tfm,
        IReadOnlyList<DependencyResult> results,
        IReadOnlyList<string> firstPartyPrefixes)
    {
        using var writer = new StreamWriter(outputPath);

        writer.WriteLine($"# Transitive Dependency Graph — {tfm}");
        writer.WriteLine();
        writer.WriteLine("*Auto-generated by [dotnet-pkgs-ai-docs](https://github.com/jmprieur/pkgs-ai-docs)*");
        writer.WriteLine();
        writer.WriteLine($"This file lists the **complete transitive dependency closure** for each package targeting **{tfm}**,");
        writer.WriteLine("computed from the actual `.nupkg` files.");
        writer.WriteLine();

        foreach (var result in results.OrderBy(r => r.PackageId, StringComparer.OrdinalIgnoreCase))
        {
            writer.WriteLine("---");
            writer.WriteLine();
            writer.WriteLine($"## {result.PackageId} {result.PackageVersion}");
            writer.WriteLine();

            // Mermaid diagram
            var mermaid = MermaidGenerator.GenerateDependencyGraph(result, firstPartyPrefixes);
            if (!string.IsNullOrEmpty(mermaid))
            {
                writer.WriteLine("```mermaid");
                writer.Write(mermaid);
                writer.WriteLine("```");
                writer.WriteLine();
            }

            // Classify dependencies
            var firstParty = result.Dependencies
                .Where(d => IsFirstParty(d.Id, firstPartyPrefixes))
                .ToList();

            var external = result.Dependencies
                .Where(d => !IsFirstParty(d.Id, firstPartyPrefixes))
                .ToList();

            if (firstPartyPrefixes.Count > 0 && firstParty.Count > 0)
            {
                writer.WriteLine("**1P packages (version managed by metapackage):**");
                foreach (var dep in firstParty)
                {
                    writer.WriteLine($"- {dep.Id} >= {dep.ResolvedVersion}");
                }
                writer.WriteLine();
            }

            if (external.Count > 0)
            {
                writer.WriteLine("**External packages (pulled in transitively):**");
                foreach (var dep in external)
                {
                    writer.WriteLine($"- {dep.Id} >= {dep.ResolvedVersion}");
                }
                writer.WriteLine();
            }

            if (result.Dependencies.Count == 0)
            {
                writer.WriteLine("*No dependencies.*");
                writer.WriteLine();
            }
        }
    }

    /// <summary>
    /// Writes one public-api-{tfm}.md file per TFM. Returns the list of files written.
    /// </summary>
    public static IReadOnlyList<string> WritePublicApiPerTfm(
        string outputFolder,
        IReadOnlyList<PublicApiResult> results)
    {
        var written = new List<string>();
        var byTfm = results
            .GroupBy(r => r.TargetFramework, StringComparer.OrdinalIgnoreCase)
            .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase);

        foreach (var tfmGroup in byTfm)
        {
            var tfm = tfmGroup.Key;
            var filePath = Path.Combine(outputFolder, $"public-api-{tfm}.md");
            WritePublicApiForTfm(filePath, tfm, tfmGroup.ToList());
            written.Add(filePath);
        }

        return written;
    }

    private static void WritePublicApiForTfm(
        string outputPath,
        string tfm,
        IReadOnlyList<PublicApiResult> results)
    {
        using var writer = new StreamWriter(outputPath);

        writer.WriteLine($"# Public API Surface — {tfm}");
        writer.WriteLine();
        writer.WriteLine("*Auto-generated by [dotnet-pkgs-ai-docs](https://github.com/jmprieur/pkgs-ai-docs)*");
        writer.WriteLine();
        writer.WriteLine($"This file lists every public type and member for each package targeting **{tfm}**.");
        writer.WriteLine("Format follows Roslyn's `PublicAPI.Shipped.txt` convention.");
        writer.WriteLine();

        foreach (var result in results.OrderBy(r => r.PackageId, StringComparer.OrdinalIgnoreCase))
        {
            writer.WriteLine("---");
            writer.WriteLine();
            writer.WriteLine($"## {result.PackageId} {result.PackageVersion}");
            writer.WriteLine();

            if (result.ApiLines.Count == 0)
            {
                writer.WriteLine("*No public API found.*");
            }
            else
            {
                writer.WriteLine("```");
                foreach (var line in result.ApiLines)
                {
                    writer.WriteLine(line);
                }
                writer.WriteLine("```");
            }
            writer.WriteLine();
        }
    }

    private static bool IsFirstParty(string packageId, IReadOnlyList<string> prefixes)
    {
        return prefixes.Any(p => packageId.StartsWith(p, StringComparison.OrdinalIgnoreCase));
    }
}
